# Generated by Django 5.0.6 on 2024-05-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerName', models.CharField(max_length=255)),
                ('VehicleNumber', models.CharField(max_length=20)),
                ('StartReading', models.IntegerField()),
                ('EndReading', models.IntegerField()),
            ],
        ),
    ]
